# Generated by Django 5.0.14 on 2026-09-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.BigAutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=30)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'Clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_empleado', models.BinaryField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('porcentaje_comision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosTurnos',
            fields=[
                ('id_servicio_turno', models.IntegerField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicios_turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='pendiente', max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
    ]
